/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedAssessmentNewRouteImport } from './routes/_authenticated/assessment.new'
import { Route as AuthenticatedSettingsPrivacyRouteImport } from './routes/_authenticated/settings.privacy'
import { Route as AuthenticatedAssessmentAttemptIdInterviewRouteImport } from './routes/_authenticated/assessment.$attemptId.interview'
import { Route as AuthenticatedAssessmentAttemptIdProcessingRouteImport } from './routes/_authenticated/assessment.$attemptId.processing'
import { Route as AuthenticatedAssessmentAttemptIdReportRouteImport } from './routes/_authenticated/assessment.$attemptId.report'
import { Route as AuthenticatedAssessmentAttemptIdResumeRouteImport } from './routes/_authenticated/assessment.$attemptId.resume'
import { Route as AuthenticatedAssessmentAttemptIdRoadmapRouteImport } from './routes/_authenticated/assessment.$attemptId.roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentNewRoute =
  AuthenticatedAssessmentNewRouteImport.update({
    id: '/assessment/new',
    path: '/assessment/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPrivacyRoute =
  AuthenticatedSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAttemptIdInterviewRoute =
  AuthenticatedAssessmentAttemptIdInterviewRouteImport.update({
    id: '/assessment/$attemptId/interview',
    path: '/assessment/$attemptId/interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAttemptIdProcessingRoute =
  AuthenticatedAssessmentAttemptIdProcessingRouteImport.update({
    id: '/assessment/$attemptId/processing',
    path: '/assessment/$attemptId/processing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAttemptIdReportRoute =
  AuthenticatedAssessmentAttemptIdReportRouteImport.update({
    id: '/assessment/$attemptId/report',
    path: '/assessment/$attemptId/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAttemptIdResumeRoute =
  AuthenticatedAssessmentAttemptIdResumeRouteImport.update({
    id: '/assessment/$attemptId/resume',
    path: '/assessment/$attemptId/resume',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAttemptIdRoadmapRoute =
  AuthenticatedAssessmentAttemptIdRoadmapRouteImport.update({
    id: '/assessment/$attemptId/roadmap',
    path: '/assessment/$attemptId/roadmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/assessment/new': typeof AuthenticatedAssessmentNewRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/assessment/$attemptId/interview': typeof AuthenticatedAssessmentAttemptIdInterviewRoute
  '/assessment/$attemptId/processing': typeof AuthenticatedAssessmentAttemptIdProcessingRoute
  '/assessment/$attemptId/report': typeof AuthenticatedAssessmentAttemptIdReportRoute
  '/assessment/$attemptId/resume': typeof AuthenticatedAssessmentAttemptIdResumeRoute
  '/assessment/$attemptId/roadmap': typeof AuthenticatedAssessmentAttemptIdRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/assessment/new': typeof AuthenticatedAssessmentNewRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/assessment/$attemptId/interview': typeof AuthenticatedAssessmentAttemptIdInterviewRoute
  '/assessment/$attemptId/processing': typeof AuthenticatedAssessmentAttemptIdProcessingRoute
  '/assessment/$attemptId/report': typeof AuthenticatedAssessmentAttemptIdReportRoute
  '/assessment/$attemptId/resume': typeof AuthenticatedAssessmentAttemptIdResumeRoute
  '/assessment/$attemptId/roadmap': typeof AuthenticatedAssessmentAttemptIdRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/assessment/new': typeof AuthenticatedAssessmentNewRoute
  '/_authenticated/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/_authenticated/assessment/$attemptId/interview': typeof AuthenticatedAssessmentAttemptIdInterviewRoute
  '/_authenticated/assessment/$attemptId/processing': typeof AuthenticatedAssessmentAttemptIdProcessingRoute
  '/_authenticated/assessment/$attemptId/report': typeof AuthenticatedAssessmentAttemptIdReportRoute
  '/_authenticated/assessment/$attemptId/resume': typeof AuthenticatedAssessmentAttemptIdResumeRoute
  '/_authenticated/assessment/$attemptId/roadmap': typeof AuthenticatedAssessmentAttemptIdRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consent'
    | '/dashboard'
    | '/progress'
    | '/assessment/new'
    | '/settings/privacy'
    | '/assessment/$attemptId/interview'
    | '/assessment/$attemptId/processing'
    | '/assessment/$attemptId/report'
    | '/assessment/$attemptId/resume'
    | '/assessment/$attemptId/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consent'
    | '/dashboard'
    | '/progress'
    | '/assessment/new'
    | '/settings/privacy'
    | '/assessment/$attemptId/interview'
    | '/assessment/$attemptId/processing'
    | '/assessment/$attemptId/report'
    | '/assessment/$attemptId/resume'
    | '/assessment/$attemptId/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/consent'
    | '/_authenticated/dashboard'
    | '/_authenticated/progress'
    | '/_authenticated/assessment/new'
    | '/_authenticated/settings/privacy'
    | '/_authenticated/assessment/$attemptId/interview'
    | '/_authenticated/assessment/$attemptId/processing'
    | '/_authenticated/assessment/$attemptId/report'
    | '/_authenticated/assessment/$attemptId/resume'
    | '/_authenticated/assessment/$attemptId/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/new': {
      id: '/_authenticated/assessment/new'
      path: '/assessment/new'
      fullPath: '/assessment/new'
      preLoaderRoute: typeof AuthenticatedAssessmentNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/privacy': {
      id: '/_authenticated/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$attemptId/interview': {
      id: '/_authenticated/assessment/$attemptId/interview'
      path: '/assessment/$attemptId/interview'
      fullPath: '/assessment/$attemptId/interview'
      preLoaderRoute: typeof AuthenticatedAssessmentAttemptIdInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$attemptId/processing': {
      id: '/_authenticated/assessment/$attemptId/processing'
      path: '/assessment/$attemptId/processing'
      fullPath: '/assessment/$attemptId/processing'
      preLoaderRoute: typeof AuthenticatedAssessmentAttemptIdProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$attemptId/report': {
      id: '/_authenticated/assessment/$attemptId/report'
      path: '/assessment/$attemptId/report'
      fullPath: '/assessment/$attemptId/report'
      preLoaderRoute: typeof AuthenticatedAssessmentAttemptIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$attemptId/resume': {
      id: '/_authenticated/assessment/$attemptId/resume'
      path: '/assessment/$attemptId/resume'
      fullPath: '/assessment/$attemptId/resume'
      preLoaderRoute: typeof AuthenticatedAssessmentAttemptIdResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$attemptId/roadmap': {
      id: '/_authenticated/assessment/$attemptId/roadmap'
      path: '/assessment/$attemptId/roadmap'
      fullPath: '/assessment/$attemptId/roadmap'
      preLoaderRoute: typeof AuthenticatedAssessmentAttemptIdRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedAssessmentNewRoute: typeof AuthenticatedAssessmentNewRoute
  AuthenticatedSettingsPrivacyRoute: typeof AuthenticatedSettingsPrivacyRoute
  AuthenticatedAssessmentAttemptIdInterviewRoute: typeof AuthenticatedAssessmentAttemptIdInterviewRoute
  AuthenticatedAssessmentAttemptIdProcessingRoute: typeof AuthenticatedAssessmentAttemptIdProcessingRoute
  AuthenticatedAssessmentAttemptIdReportRoute: typeof AuthenticatedAssessmentAttemptIdReportRoute
  AuthenticatedAssessmentAttemptIdResumeRoute: typeof AuthenticatedAssessmentAttemptIdResumeRoute
  AuthenticatedAssessmentAttemptIdRoadmapRoute: typeof AuthenticatedAssessmentAttemptIdRoadmapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedAssessmentNewRoute: AuthenticatedAssessmentNewRoute,
  AuthenticatedSettingsPrivacyRoute: AuthenticatedSettingsPrivacyRoute,
  AuthenticatedAssessmentAttemptIdInterviewRoute:
    AuthenticatedAssessmentAttemptIdInterviewRoute,
  AuthenticatedAssessmentAttemptIdProcessingRoute:
    AuthenticatedAssessmentAttemptIdProcessingRoute,
  AuthenticatedAssessmentAttemptIdReportRoute:
    AuthenticatedAssessmentAttemptIdReportRoute,
  AuthenticatedAssessmentAttemptIdResumeRoute:
    AuthenticatedAssessmentAttemptIdResumeRoute,
  AuthenticatedAssessmentAttemptIdRoadmapRoute:
    AuthenticatedAssessmentAttemptIdRoadmapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
